### ISSUE TITLE
Error: move_base process died [pid 22744, exit code -6

### ISSUE THREAD

**Issue by chetanchandc** [pal-robotics/tiago_navigation#11] opened 2022-05-30 18:59 UTC
Hello, pal-robotics!

Firstly, Thanks for the TIAGo packages. 
I am working on the TIAGo navigation package. After successful installation of the TIAGo workspace, I complied the package and RUN tiago_navigation.launch file. Unfortunately, It's unable to localize and navigate the robot TIAGo and I am receiving these errors...

![move_base](https://user-images.githubusercontent.com/62232861/171045950-af46674e-c293-4117-86c2-993874269ca9.png)

As of termination error, I tried installing the range-sensor-layer plugin but, it did not solve the issue.
Also, I have debugged the global planner and local planner parameter (**.yaml**) files. But, unable to troubleshoot the issue. 

Would you please let me know if I was missing something and what's the exact issue and the reason for the error? Your answer would help me a lot.

Thank you very much!

**Comment by saikishor** [comment] 2022-05-31 08:45
Hello @chetanchandc ,

Thank you for showing interest in our TIAGo simulation. Regarding your issue, I think that the compilation was successful but it didn't link against the library it is supposed to link. We recommend you to clean your workspace, remove the old catkin configuration, source `/opt/ros/melodic/setup.bash` and the compile it. It should be fixed. In case it is not fixed, you can see the info of the library it is linked against using the following command `ldd /home/trayach/tiago_public_ws/devel/lib/librange_sensor_layer.so`, this should give you some idea on the issue.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-05-31 10:39
It resolved! Thank You.

**Comment by saikishor** [comment] 2022-05-31 10:40
Hello @chetanchandc ,

Thank you for letting us know. We are glad it works for you. Have a great time with our TIAGo Simulation!.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-06-01 09:56
Hello @saikishor, 

Sorry to bother you. After the above working fine with the maps available in the Tiago workspace, I have integrated the Tiago environment into my work. 

For example, I already have (my) world and map files which I previously worked on with a simple mobile robot. 
So, when I implement the amcl and move_base node to my simple robot, my world and map, the navigation works fine.

Whereas, when I try to integrate my world and map(which I have used in my work) into the Tiago environment, the 2d nav goal is not working. 
![Screenshot from 2022-06-01 11-41-15](https://user-images.githubusercontent.com/62232861/171377740-bcc7f835-95ef-4f41-93d8-c36e86d9dbc6.png)

Would you let me know what's the exact issue? 
Thank you!

**Comment by saikishor** [comment] 2022-06-01 10:27
Hello @chetanchandc,

Thanks for getting back to us with your issue. It's very hard to understand the right cause of the issue just by a brief description. Unfortunately, We cannot help you much with the current info, unless there are some error logs or some crash logs. 

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-06-05 21:21
Hello @saikishor,

Sorry for the late reply. 
I am receiving the below warning INFO when I assign a `2d nav goal` to the robot. Of course, the robot is not moving but is able to plan its trajectory.

![Screenshot from 2022-06-05 21-54-06](https://user-images.githubusercontent.com/62232861/172069579-82ec48db-6e80-41a7-931b-1430afe89e91.png)

Can you help me with this? 

Thank You!

**Comment by saikishor** [comment] 2022-06-07 07:40
Hello @chetanchandc,

As the warning shown in the terminal, the the rgbd scan data was not updated, in that case the  the robot will be not allowed to move for the safety reasons, as it doesn't make sense to navigate when there is no up-to-date information from the sensors. Probably the node didn't start, check in your launch file,if you have this node running or not . https://github.com/pal-robotics/tiago_simulation/blob/kinetic-devel/tiago_2dnav_gazebo/launch/tiago_navigation.launch#L90-L94. We hope this helps to solve your issue.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-06-07 09:17
Hi @saikishor, 

Thanks for letting me know! 
I tried as for your suggestion. But, I assume that's not the exact reason for the error. The map configuration path (which I set earlier) was wrong respective to its desired location(mistake is mine). That's the reason for the failure of the `move_base` node. 

I have now modified the path of the `$(env HOME)/.pal/tiago_maps/configurations/$(arg world)` and then navigation works pretty fine.

Thanks for guiding me through this!

**Comment by chetanchandc** [comment] 2022-06-22 07:09
Hello @saikishor,

After previous issues, I have completed my simulation and it works fine. Even though I did not modify any files after completing my simulation, recently I came across the following errors.
`[ERROR] [1655880837.460069669]: Couldn't find filter of type pal_filters/LaserScanOutlierFilter`
and also these
![Screenshot from 2022-06-22 08-41-07](https://user-images.githubusercontent.com/62232861/174964572-b2c2d746-12f0-4a43-b427-282300c69a29.png)

Also, I have clean my workspace and compile it again. Would you please let me know the exact issue? 
Moreover, this issue was raised after working on the real robot TIAGo.

Thank you!

**Comment by saikishor** [comment] 2022-06-22 09:39
Hello @chetanchandc,

Thank you for writing to us. Regarding your issue, can you please let us know how exactly your are building your workspace. We would like to know if you are using development machine or a machine with standard ROS?. Moreover, when you said you have this issue while working on real TIAGo robot, can you give us more details to reproduce it or the steps you have followed. This information would help us to understand the issue better.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-06-22 14:07
Firstly, Thanks for the reply! @saikishor 

1. I am using `catkin build -c` to build my _tiago_public_ws_ and sourcing using `source devel/setup.bash`. Until here everything goes fine more or less with some errors in building packages that are not related to _tiago_public_ws_, but every package related to _tiago_public_ws_ builds fine. 
2. I am using ubuntu 18.04 (dual boot) and ROS melodic.
3. Concerning the real robot, firstly I have connected the robot to my laptop and then modified the ROS_IP and ROS_MASTER_URI. Now i opened rviz to visualize the map and launched my work(where the robot stuck here in real robot) and after disconnecting the robot and started simulation in my workspace. The above errors appear, which haven't appeared previously. 

I hope I understood your question and replied correctly.

Regards 
Chetan

**Comment by saikishor** [comment] 2022-06-22 14:42
Hello @chetanchandc,

Regarding steps 1 and 2, seems to be fine. I think in step 3 trying to launch the simulation with the ROS_IP and ROS_MASTER_URI might be causing this issue. 

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by chetanchandc** [comment] 2022-06-22 14:54
Thanks for the fast reply @saikishor,

I understand, but the above errors occurred when I launch the simulation in my workspace (i.e., when not working with the robot).

Regards
Chetan

**Comment by saikishor** [comment] 2022-06-22 14:58
Hello @chetanchandc,

Thanks for the confirmation. Please make sure that you launch the navigation and setup with the proper argument of `public_sim:=true`. If not it might cause these problems, the package errors you mentioned above are PALs proprietary software, and it is not available alongside the public simulation.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by procopiostein** [comment] 2022-06-22 15:07
@chetanchandc what does this have to do with the initial issue in this ticket?
this is not a helpdesk. if you have an issue, please due a proper due dilligence and investigation and then create a ticket with the most possible information.
the original issue was fixed. why do you keep reopening the ticket?

again, this is not a helpdesk for you to ask for help each time something goes wrong in your execution. investigate it better, go to answer.ros.org and ask there, for example.

**Closed as completed by procopiostein** 2022-06-22 15:07 UTC
